--- test
- hosts: all
  gather_facts: true
  tasks:
    - name: restart a container
  docker_container:
    name: activemq
    image: henninb/activemq
    state: started
    restart: yes
    env:
        SECRET_KEY: "ssssh"
        # Values which might be parsed as numbers, booleans or other types by the YAML parser need to be quoted
        BOOLEAN_KEY: "yes"
