version: "3.7"
services:
  varnish-server:
    image: varnish
    # user: "${CURRENT_UID}:${CURRENT_GID}"
    container_name: varnish-server
    ports:
      - "8080:80"
    expose:
      - "8080"
    volumes:
      - ./default.vcl:/default.vcl
