version: "3.7"
services:
  varnish-server:
    image: varnish
    # user: "${CURRENT_UID}:${CURRENT_GID}"
    container_name: varnish-server
    ports:
      - "9090:8080"
    expose:
      - "9090"
    volumes:
      - ./default.vcl:/etc/varnish/default.vcl
